### ISSUE TITLE
spike (2 days) - notification emails via python

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/dp-python-tools#14]
Check for this on ONSdigital github.

## What is this

We need a reusable bit of software to send email notifications.

## What to do

Look at the options for sending an email via python and make comparissons between them to be fed back to the team.

Ideally, we'd want an example or two but pure research is fine as well, we want to compare the options on:

- complexity
- dependencies - i.e, what external things (like mail servers) if any are needed
- reliability - i.e if external packages are involved, how much are they used? how long since they were updated? are there many open issues on the repository?

You'll probably need an SMTP server, there's some sort of AWS service for this, its worth investigating that and how/if we can utilise it via boto3 (or any alternative aws compliant package).

## Accetpance Critiera

- [x] Present the findings back to the team.

I'm not bothered how you present this information back: slides and a chat, a write up, example on a branch somewhere - whatever forum you're most comfortable with that gets the information accross is fine.

**Comment by Moasib-Arif** [comment]
For this ticket I test different solution that we could use to send emails via python.

In this presentation (https://docs.google.com/presentation/d/1omD9T7ISZCqK9keZiacSWiEWpYJSptTetYLFun92Xns/edit?usp=sharing ) I covered the different solutions

1. SMTPLib (SMTP) : Python's built-in SMTP library. 
2. Smtplib and others Python library for sending emails(Mime + Email). 
3. Boto3: AWS SDK for Python to interact with AWS services.
4. Third-party packages: e.g., yagmail, sendgrid

Useful resources: https://realpython.com/python-send-email/ 
* Setting up a Local SMTP Server

Additional Notes: Secure SMTP Connection / Encryption ( SSL Library) 
https://docs.python.org/3/library/ssl.html

ONS existing solution 
<img width="1492" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzR4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12f1532453c1d0a275367ef96a9a86687ab2929c/Pasted%20Graphic%2010.png" alt="Pasted Graphic 10.png" />


Code Solutions:

I initially used the Python built in SMTP library to send email on local server ( Requires SMTP. Server)

This code is used to send Plain test emails only.
<img width="654" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEF4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee79fa9c10d642077f97deb665d91bb7a54259c8/image.png" alt="image.png" />


If we want to add HTML Content to email we can do like this 

Side Note (Difference between HTML email and plain email ( a plain text email contains only text—no images, stylised fonts, or hyperlinks.) 


(HTML, which stands for HyperText Markup Language, is a way to code a document (made out of ASCII text) that lets an HTML reader (such as a web browser) know how to render certain types of information.
HTML have everything plain text emails don’t have: colour, style, images, and sometimes multimedia.)

Code Example:

<img width="549" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEV4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b4468cf488e7a4b7acf2aaf437b29018f420e35/image.png" alt="image.png" />


If you want to attach pdf or file to an email you can do this by using the Email and Mime library

<img width="1046" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE14QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0417f2d1354b85688c090a6c455a86e51fea3a38/image.png" alt="image.png" />

SMTP Review:

<img width="1429" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFV4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5969dc43310315e3784eb51abb602f19218a8eb7/image.png" alt="image.png" />


<img width="1527" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFl4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad2fb187ba9c103b99eaf5e30a39a42d85868340/image.png" alt="image.png" />



Additionally AWS offers services to send email . Amazon SES and Boto3 

Amazon SES is a cloud-based email service provider that can integrate into any application for high volume email automation.

AWS SES need to configured in AWS Console ( Website ) before we can embed that in our code 

Note: Before you can send an email (. The email address needs to be verified 

<img width="417" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGN4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c72b47ea8d5218e8ea132c3499fa09944ba16b5/image.png" alt="image.png" />


You can also send HTML email using the AWS like this 

<img width="495" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGd4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c30efdafc468c9035a53c21f6d361ebd103d7f7e/image.png" alt="image.png" />


AWS Review
<img width="1496" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGt4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8aa7b710f53c3b54ffdd2a5d8224285427e1a817/image.png" alt="image.png" />


These are alternative solution available such as yagmail and sendgrid

<img width="1415" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG94QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49123697d5e83d933f881a883cc04bfe2b3cd9a7/image.png" alt="image.png" />

<img width="1409" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHN4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f7ce4c585a75cec7c200237339f2185e17cf576/image.png" alt="image.png" />

**Comment by Moasib-Arif** [comment]
Addtional Note: AWS Code solution need furture configration set up to fully send the content of the email to ONS email. During testing I could send an email to another email with subject and content however the recipient cannot view the content as they get this error "Your message wasn't delivered because the recipient's email provider rejected it."
 
I did some research and the issue is with ONS DMARC Policy and we can fix this issue if we verify the domain and update the DNS record to ONS domain's DNS configuration.
