### ISSUE TITLE
spike (1 day) - triggering airflow DAGS with python

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/dp-python-tools#15]
## What is this

We'll want to be able to trigger airflow DAGs from python.

It feels like a common use case so have a look around for packages or plugins to do this.

_ideally_ it'd be pure python rather than a plugin as it'd be nice to reuse the same component to trigger the initial DAG from a lambda, but I'm not wedded to it, be practical. Airflow also has an api so working our how to trigger a dag via an api PUT/POST wold also be of use.

## What to do

Investigate the options and try and implement a few different ways of doing this.

Spin up a local airflow via [this](https://github.com/aws/aws-mwaa-local-runner) and (I think, read the docs) `docker-compose up`  to use while developing/playing.

## Accetpance Critiera

- [ ] Feed back to the team examples of how to trigger airflow Dags with python.

**Comment by SarahJohnsonONS** [comment]
Clone or fork the [AWS MWAA local runner](https://github.com/aws/aws-mwaa-local-runner) repo - my fork is here: https://github.com/SarahJohnsonONS/aws-mwaa-local-runner

The README is very helpful - follow the instructions in the "Get started" section to build the image and then run the local Airflow environment to see the DAGs that have already been created.

I followed [this tutorial](https://airflow.apache.org/docs/apache-airflow/stable/tutorial/fundamentals.html) in `my_other_dag.py`, and created my own DAG in `my_dag.py`, based on the decorator approach [here](https://airflow.apache.org/docs/apache-airflow/stable/tutorial/taskflow.html).

Next steps: figure out how to use the [Airflow REST API](https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html) and/or the [Airflow Python client](https://github.com/apache/airflow-client-python).
