### ISSUE TITLE
spike (2 days) - virtual environments on airflow

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/dp-python-tools#16]
## What is this

You should be able to spin up a local instance of apache airlfow using: https://github.com/aws/aws-mwaa-local-runner

This should get you to the point where you have a local airflow with a sample DAG in it.

This task is to investigate using https://airflow.apache.org/docs/apache-airflow/stable/howto/operator/python.html#externalpythonoperator to run airflow tasks in **specific and pre-built** virtual environemnts.

_Note: avoid any implementations that build the venv when the task runs, there's a lot of overhead there._

In simplest terms our goals are:
- DEs will need one set of python packages - so use a "DE venv" for it.
- SEs will need a different set of python packages - so use a "SE venv" for it.

We want to invesigate the feasibility of managing this via the linked airflow operator.

## What to do

- Sping up a local airflow, there should be instructions in the repo
- Create two named virtual environments, use [venv](https://docs.python.org/3/library/venv.html) please, that seems to be the tool of choice for airflow.
- See if you can figure out how to rebuild these while the airflow server is running.
- Make two very simple dags, one each to run some very very simple python using each of the virtual environments.

I know there's a "script" facility in airflow somewhere. Ideally a script creates the virtual environments on startup and we can do one of:
- press a button somewhere to rebuild them
- send a command to the airflow api telling it to run the scripts

(optional but nice to have) figure out how to create the named venvs with pipenv rather than venv.

## Acceptance Criteria

- [ ] Example created of how to run a task within an airflow DAG using a pre-made virtual env.
- [ ] Findings shared with the team via a demoonstration.
- [ ] (Optional) create the virtual environments with pipenv.

**Comment by nimshi89** [comment]
Okay so, findings regarding the ticket:

I have used the `aws-mwaa-local-runner` to set up a local instance of apache airlfow . 
https://github.com/aws/aws-mwaa-local-runner?tab=readme-ov-file Just follow the Readme file instructions and it is quite straight forward. 

after that create a separate DAG file within the DAGS folder 

<img width="984" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3d3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44550ab585b1109099cf636ef50fc16c5e51a047/Screenshot%202024-02-06%20at%2010.40.53.png" alt="Screenshot 2024-02-06 at 10.40.53.png" />

I just simply copied the example DAG file that come with the local runner. 
it shows how to create tasks and what tags to use.

To create a venv (virtual Enviorment) on the aws I took this example:
`https://airflow.apache.org/docs/apache-airflow/stable/howto/operator/python.html#externalpythonoperator`

and details to look out for (sadly they weren’t so obvious to me :D ):
make sure the tasks are not named the same (the one on top), and the `python=PATH_TO_PYTHON_BINARY` is for a path to the python binary file within the environment.

 <img width="1846" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG93QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d17c9a3ecba8402cdee01b1211040d808e47690/Screenshot%202024-02-06%20at%2010.48.20.png" alt="Screenshot 2024-02-06 at 10.48.20.png" />

Testing to use a different module within he virtual environment:
I have called the `import requests` and executed a simple task to get the `statuscode` for `http://localhost:7878`.
the task ran without an error which show it is working as expected . 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUl3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2af7aae8ef5a4431e244180dec1c9628b73c070e/Screenshot%202024-02-06%20at%2010.51.45.png" alt="Screenshot 2024-02-06 at 10.51.45.png" />

<img width="1522" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXd3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--704c35e7a4b267be0783fadac66abc5e7302691c/Screenshot%202024-02-06%20at%2010.55.01.png" alt="Screenshot 2024-02-06 at 10.55.01.png" />

The key was to make sure it is called within the function that uses the virtual environment . 

If this is not detailed enough or the test is not quite what we need please let me know. Some part of this ticket was quite confusing so I don't want to miss anything.
